### ISSUE TITLE
System.MissingMethodException after upgrading to Akka.NET 1.5

### ISSUE THREAD

**Issue by object** [petabridge/Akka.Persistence.Extras#205]
Apparently Akka.Persistence.Exras needs to be rebuilt with new Akka libraries. Running them with Akka.NET 1.5 causes the following error:

Method not found: 'Void Akka.Event.ILoggingAdapter.Error(System.String, System.Object[])'.

at Akka.Persistence.Extras.PersistenceSupervisor.OnTerminated(Object message)
at Akka.Persistence.Extras.PersistenceSupervisor.Receive(Object message)
at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
at Akka.Actor.ActorCell.ReceiveMessage(Object message)
at Akka.Actor.ActorCell.Invoke(Envelope envelope)

This is a showstopper for upgrading to Akka.NET 1.5 for those using PersistenceSupervisor.

**Comment by mrbenzu** [comment]
I have the same issue
My PR
https://github.com/petabridge/Akka.Persistence.Extras/pull/203

**Comment by mrbenzu** [comment]
PR has been merged but there is some issue with azure pipeline to release package.
@Arkatufus Can you take look?
https://github.com/petabridge/Akka.Persistence.Extras/runs/12092679245

**Comment by object** [comment]
Looks like there is a dependency on an old version of Visual Studio:

"An image label with the label VS2017 does not exist."

Can you please look at it @Arkatufus, we are dependent on this package to upgrade our solution to Akka.NET 1.5.

**Comment by Aaronontheweb** [comment]
We just shipped 1.5.1 today: https://github.com/petabridge/Akka.Persistence.Extras/releases/tag/1.5.1 - fixed the issue with the build pipeline. Thank you everyone for your PRs and for bringing this to our attention!
